# Generated by Django 4.2 on 2023-04-05 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topics',
            old_name='title',
            new_name='name',
        ),
    ]
